### ISSUE TITLE
ToDo until submission

### ISSUE THREAD

**Issue by vGsteiger** [vGsteiger/Lucky38#3]
- [x] Add functionality of player name
- [x] Test Contract on friday
- [x] Add howto to use contract on website (how to use remix)

**Comment by TK5-Tim** [comment]
@vGsteiger  ist die Erklärung der Benutzung so in Ordnung?

**Comment by TK5-Tim** [comment]
Add functionality of player name wird nicht implementiert, da die Größe des Contracts da nicht mitmacht.
